service: serverless-todo-app

plugins:
  - serverless-iam-roles-per-function

frameworkVersion: '4.6.1'

provider:
  name: aws
  runtime: nodejs18.x
  tracing:
    lambda: true
    apiGateway: true


environment:
    TODO_TABLE: Todo-${self:provider.stage}
    //IMAGES_TABLE: Images-${self:provider.stage}
    //IMAGE_ID_INDEX: ImageIdIndex
    //IMAGES_S3_BUCKET: dktest202402-todo-images-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300

iam:
  role:
    statements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODO_TABLE}
    - Effects: Allow
      Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
      Resource:
          - *

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # TODO: Configure this function  - dktest - not tested
  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos

  # TODO: Configure this function - dktest - not tested
  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          authorizer: Auth
          path: todos
          cors: true
          request:
            schemas:
              application/json: ${file(models/create-task-request.json)}

  # TODO: Configure this function
  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}

  # TODO: Configure this function
  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}

  # TODO: Configure this function
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment

resources:
  Resources:
    # TODO: Add any necessary AWS resources